# Generated by Django 4.0.6 on 2022-08-04 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_p',
            fields=[
                ('category_p', models.AutoField(default='01', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default='0')),
                ('category_image', models.ImageField(upload_to='media/category')),
            ],
        ),
        migrations.CreateModel(
            name='surfaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_id', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('surface_image', models.ImageField(upload_to='media/surface')),
                ('glass_or_aluminium', models.CharField(max_length=50)),
                ('category_surface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category_p')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField()),
                ('model', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=50)),
                ('tone_of_color', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('opacity', models.CharField(max_length=50)),
                ('deleted', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/product')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category_p')),
                ('product_surface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.surfaces')),
            ],
        ),
    ]
