# Generated by Django 4.0.6 on 2022-08-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_p',
            name='category_p',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
