# Generated by Django 4.0.6 on 2022-08-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_category_p_category_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_p',
            old_name='category_p',
            new_name='category_id',
        ),
    ]
