# Generated by Django 4.0.6 on 2022-08-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_category_p_category_p_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_surface',
        ),
        migrations.RemoveField(
            model_name='surfaces',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default='0'),
        ),
        migrations.AddField(
            model_name='surfaces',
            name='is_active',
            field=models.BooleanField(default='0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='surfaces',
            name='surface_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
