# Generated by Django 4.0.6 on 2022-08-04 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_product_id_remove_product_product_surface_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_surface',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.surfaces'),
            preserve_default=False,
        ),
    ]
