# Generated by Django 4.0.6 on 2022-08-05 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_product_surface'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surfaces',
            name='glass_or_aluminium',
        ),
    ]
