# Generated by Django 3.2.1 on 2022-08-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220808_2037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='product_s',
        ),
    ]
